---
title: Siteleaf Boilerplate
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
navigation:
- title: Link 1
  subfolderitems:
  - title: Sub Link 1
    url: "/thing1.html"
  - title: Sub Link 2
    url: "/thing2.html"
  - title: Sub Link 3
    url: "/thing3.html"
- title: Link 2
  url: "/link2"
- title: Link 3
  url: "/link3"
baseurl: ''
url: ''
sass:
  style: compressed
plugins:
- jekyll-feed
